package edu.pucmm.eict.util;

import org.h2.jdbcx.JdbcDataSource;

import javax.sql.DataSource;
import java.sql.Connection;
import java.sql.SQLException;
import java.sql.Statement;

public class Database {
    private static JdbcDataSource dataSource;

    public static synchronized void init() {
        if (dataSource != null) return;
        String mode = System.getProperty("APP_DB_MODE", System.getenv("APP_DB_MODE"));
        if (mode == null || mode.isEmpty()) mode = "file"; // dev por defecto en archivo
        String jdbcUrl;
        if ("mem".equalsIgnoreCase(mode)) {
            jdbcUrl = "jdbc:h2:mem:acortador;DB_CLOSE_DELAY=-1";
        } else {
            String baseDir = System.getProperty("user.dir");
            String path = baseDir + "/data/acortador";
            jdbcUrl = "jdbc:h2:file:" + path + ";AUTO_SERVER=TRUE";
        }
        dataSource = new JdbcDataSource();
        dataSource.setURL(jdbcUrl);
        dataSource.setUser("sa");
        dataSource.setPassword("");

        // Crear esquema si no existe
        try (Connection c = dataSource.getConnection(); Statement st = c.createStatement()) {
            st.executeUpdate("CREATE TABLE IF NOT EXISTS usuarios (\n" +
                    "  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,\n" +
                    "  username VARCHAR(100) NOT NULL UNIQUE,\n" +
                    "  password VARCHAR(255) NOT NULL,\n" +
                    "  role VARCHAR(30) NOT NULL\n" +
                    ")");

            st.executeUpdate("CREATE TABLE IF NOT EXISTS urls (\n" +
                    "  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,\n" +
                    "  original_url VARCHAR(2048) NOT NULL,\n" +
                    "  short_url VARCHAR(32) NOT NULL UNIQUE,\n" +
                    "  access_count INT NOT NULL DEFAULT 0,\n" +
                    "  user_id BIGINT,\n" +
                    "  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,\n" +
                    "  expires_at TIMESTAMP NULL,\n" +
                    "  CONSTRAINT fk_url_user FOREIGN KEY (user_id) REFERENCES usuarios(id) ON DELETE SET NULL\n" +
                    ")");

            st.executeUpdate("CREATE TABLE IF NOT EXISTS access_details (\n" +
                    "  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,\n" +
                    "  url_id BIGINT NOT NULL,\n" +
                    "  timestamp TIMESTAMP NOT NULL,\n" +
                    "  browser VARCHAR(100),\n" +
                    "  ip VARCHAR(64),\n" +
                    "  client_domain VARCHAR(255),\n" +
                    "  platform VARCHAR(100),\n" +
                    "  CONSTRAINT fk_access_url FOREIGN KEY (url_id) REFERENCES urls(id) ON DELETE CASCADE\n" +
                    ")");

            // índices
            st.executeUpdate("CREATE INDEX IF NOT EXISTS idx_urls_expires_at ON urls(expires_at)");
            st.executeUpdate("CREATE INDEX IF NOT EXISTS idx_urls_user_id ON urls(user_id)");
            st.executeUpdate("CREATE INDEX IF NOT EXISTS idx_access_url_id ON access_details(url_id)");
        } catch (SQLException e) {
            throw new RuntimeException("Error initializing database schema", e);
        }
    }

    public static DataSource getDataSource() {
        if (dataSource == null) init();
        return dataSource;
    }
}
